quarkus:
  mongodb:
    connection-string: ${MONGO_CONNECTION_STRING}
    database: ${MONGO_DATABASE}
  http:
    cors:
      ~: true
      access-control-max-age: 24H
      headers: Content-Type, Authorization, X-Requested-With
      methods: GET, POST, PUT, DELETE
      origins: ${UI_URL}
      exposed-headers: Authorization
  native:
    resources:
      includes: ${JWT_PUBLIC_KEY_PATH}, ${JWT_PRIVATE_KEY_PATH}

mp:
  jwt:
    verify:
      issuer: onetalk-api
      lifespan: 900 # 15 minutos
      publickey: ${JWT_PUBLIC_KEY_PATH}

smallrye:
  jwt:
    sign:
      key: ${JWT_PRIVATE_KEY_PATH}