quarkus:
  mongodb:
    connection-string: ${MONGO_CONNECTION_STRING}
    database: ${MONGO_DATABASE}
  http:
    cors:
      ~: true
      access-control-max-age: 24H
      headers: Content-Type, Authorization, X-Requested-With
      methods: GET, POST, PUT, DELETE
      origins: http://localhost:5173
      exposed-headers: Authorization

  native:
    resources:
      includes: publicKey.pem, privateKey.pem

mp:
  jwt:
    verify:
      issuer: onetalk-api
      lifespan: 900 # 15 minutos
      publickey:
        location: ${JWT_PUBLIC_KEY_PATH}

smallrye:
  jwt:
    sign:
      key:
        location: ${JWT_PRIVATE_KEY_PATH}